name: SimpleMail
main: me.odium.test.SimpleMailPlugin
version: 0.3.8

depend: [Monolith]

commands:
   mail:
      aliases: [simplemail]
      description: Display Help Menu
      permission: SimpleMail.inbox
      usage: /mail
   sendmail:
      description: Send mail to a user
      permission: SimpleMail.sendmail
      usage: /sendmail <player> <message>
   inbox:
      description: View your inbox
      permission: SimpleMail.inbox
      usage: /inbox
   outbox:
      description: View your outbox
      permission: SimpleMail.outbox
      usage: /outbox
   readmail:
      description: Read a message
      permission: SimpleMail.inbox
      usage: /readmail <id>
   delmail:
      description: delete a message
      permission: SimpleMail.inbox
      usage: /delmail <id>
   sentby:
      description: Find messages sent by a username; supports % sign for wildcard
      permission: SimpleMail.admin
      usage: /sentby
   sentto:
      description: Find messages sent to a username; supports % sign for wildcard
      permission: SimpleMail.admin
      usage: /sentto
   mailboxes:
      description: View active mailboxes; supports % sign for wildcard
      permission: SimpleMail.admin
      usage: /mailboxes <MaxRecords> <FilterString>
   clearmailbox:
      description: Clear an active mailbox (delete messages received by player)
      permission: SimpleMail.admin
      usage: /clearmailbox <player>
   purgemail:
      description: Purge expired messages from database
      permission: SimpleMail.admin
      usage: /purgemail
