name: SimpleMail
main: me.odium.test.simplemail
version: 0.1
commands:
   mail:
      description: Display Help Menu
      permission: SimpleMail.inbox
      usage: /delmail <id>
   sendmail:
      description: tester
      permission: SimpleMail.sendmail
      usage: /sendmail <player> <message>
   inbox:
      description: inbox
      permission: SimpleMail.inbox
      usage: /inbox
   readmail:
      description: readmail
      permission: SimpleMail.inbox
      usage: /readmail <id>
   delmail:
      description: readmail
      permission: SimpleMail.inbox
      usage: /delmail <id>
   mailboxes:
      description: view active mailboxes
      permission: SimpleMail.admin
      usage: /mailboxes
   clearmailbox:
      description: clear an active mailbox
      permission: SimpleMail.admin
      usage: /clearmailbox <player>